### ISSUE TITLE
Small issues in SystemExitCallInterceptionAction

### ISSUE THREAD

**Issue by MarcMazas** [dotxyteam/SwingTestingToolkit#3]
Hi. 
I used the concurrency.Flipper app from the Swing tutorial.
I recorded a test script with 3 actions (CallMainMethodAction, ClickAction on Start button, ClickAction on Stop button).
I added in the .stt file a 4th action (CloseWindowAction).
Test execution is fine.

I added in the .stt file a 5th action, with oppposite set to false and then true:
```
    <xy.ui.testing.action.SystemExitCallInterceptionAction>
      <oppposite>false</oppposite>
    </xy.ui.testing.action.SystemExitCallInterceptionAction>

```
* false says:
21 nov. 2024 16:06:11 [xy.ui.testing.Tester@31f924f5] INFO - Replaying action no5: Do not intercept System.exit() calls
... but throws a SecurityException when clicking on the close icon:
Exception in thread "AWT-EventQueue-0" java.lang.SecurityException: System.exit() call intercepted
    at xy.ui.testing.action.SystemExitCallInterceptionAction$NoExitSecurityManager.checkExit(SystemExitCallInterceptionAction.java:99)
    at java.lang.Runtime.exit(Runtime.java:101)
... what does not close the window

* true says:
21 nov. 2024 16:01:23 [xy.ui.testing.Tester@31f924f5] INFO - Replaying action no5: Intercept System.exit() calls
... but immediately fails as no SecurityManager has been established
21 nov. 2024 16:01:24 [xy.ui.testing.Tester@31f924f5] ERROR - java.lang.NullPointerException
    at xy.ui.testing.action.SystemExitCallInterceptionAction.disableInterception(SystemExitCallInterceptionAction.java:51)
    at xy.ui.testing.action.SystemExitCallInterceptionAction.execute(SystemExitCallInterceptionAction.java:40)
    at xy.ui.testing.Tester$3.run(Tester.java:287)
    at xy.ui.testing.util.MiscUtils$3.run(MiscUtils.java:211)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
... and the window can be closed

So at that point I see that:
a) the log messages are interverted: false should say "Intercept..." and true sould say "Do not intercept..."
b) the disableInterception() method does not check nullity of System.getSecurityManager()

Then I added a same 6th action, with false in the 5th and true in the 6th:
```
    <xy.ui.testing.action.SystemExitCallInterceptionAction>
      <oppposite>true</oppposite>
    </xy.ui.testing.action.SystemExitCallInterceptionAction>

```* 2nd action with true; that now says:
21 nov. 2024 16:47:06 [xy.ui.testing.Tester@31f924f5] INFO - Replaying action no5: Do not intercept System.exit() calls
21 nov. 2024 16:47:06 [xy.ui.testing.Tester@31f924f5] INFO - Replaying action no6: Intercept System.exit() calls
... and now no exception (as the 5th action created a NoExitSecurityManager(null))
... and the window can still be closed

**Comment by dotxyteam** [comment]
Hello,
You are right. The logic in the SystemExitCallInterceptionAction.execute(...) method was inverted. It is now fixed and the System.getSecurityManager() is checked.
Regards
